/** @typedef {{ id: string, slug: string, name: string, type?: string, description?: string|Record<'en'|'es', string>, price: number|null, currency: string, category: string, images: string[]|Record<string, string>, cardPreviewSide?: 'front'|'back', imageFit?: 'cover'|'contain', sizes?: string[], variants?: { id: string, size?: string, available?: boolean, options?: object }[], colors?: string[], sizeGuide?: { referenceSize:string, widthCm:number, lengthCm:number, shoulderSleeveCm:number, temporary?:boolean }, featured?: boolean, available?: boolean, shipping: { weightKg:number, widthCm:number, heightCm:number, lengthCm:number, temporary?:boolean }|null, createdAt: string }} Product */

const TSHIRT_DESCRIPTION = Object.freeze({
  es: 'Remera oversize confeccionada en 100% algodón, de calce amplio y caída relajada. Cuello reforzado y construcción pensada para uso diario.',
  en: 'Oversized T-shirt made from 100% cotton, with a relaxed fit and loose silhouette. Reinforced collar and construction designed for everyday wear.'
});

// TODO before production: replace these temporary folded-package dimensions with measured packaging data.
const TSHIRT_SHIPPING = Object.freeze({ weightKg: 0.3, widthCm: 30, lengthCm: 25, heightCm: 5, temporary: true });
// Temporary garment measurements for the published oversized T-shirt reference size; never use these as package dimensions.
const TSHIRT_SIZE_GUIDE = Object.freeze({ referenceSize: 'L', widthCm: 64, lengthCm: 75, shoulderSleeveCm: 48, temporary: true });

/** @type {Product[]} */
export const products = [
  {
    id: 'lain-tee-02',
    slug: 'lain-tee-02',
    name: 'LAIN T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/lain-frente.webp', back: '/img/outfit/web/lain-espalda.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-09-28'
  },
  {
    id: 'lain-tee-01',
    slug: 'lain-tee-01',
    name: 'PHANTOMA T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/phantoma1.webp', back: '/img/outfit/web/phantoma.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-09-15'
  },
  {
    id: 'lain-tee-03',
    slug: 'lain-tee-03',
    name: 'LAIN WIRED T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/lain-wired-frente.webp', back: '/img/outfit/web/lain-wired-espalda.webp' },
    cardPreviewSide: 'back',
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-09-28'
  },
  {
    id: 'lain-tee-06',
    slug: 'lain-tee-06',
    name: 'LAIN POSTER WHITE T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/lain-poster-frente-blanco.webp', back: '/img/outfit/web/lain-poster-espalda-blanco.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-09-28'
  },
  {
    id: 'lain-tee-10',
    slug: 'lain-tee-10',
    name: 'CAT T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/remera-frente-cat.webp', back: '/img/outfit/web/remera-espalda-cat.webp' },
    cardPreviewSide: 'back',
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-09-28'
  },
  {
    id: 'lain-tee-07',
    slug: 'lain-tee-07',
    name: 'LAIN DEREALIZATION T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/remera-frente-lain.webp', back: '/img/outfit/web/remera-espalda-lain.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-10-08'
  },
  {
    id: 'lain-tee-08',
    slug: 'lain-tee-08',
    name: 'THE SMITHS T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/remera-frente-thesmiths.webp', back: '/img/outfit/web/remera-espalda-thesmiths.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-10-08'
  },
  {
    id: 'lain-tee-11',
    slug: 'lain-tee-11',
    name: 'ANTI SOCIAL T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/remera-frente-antisocial.webp', back: '/img/outfit/web/remera-espalda-antisocial.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-10-08'
  },
  {
    id: 'lain-tee-12',
    slug: 'lain-tee-12',
    name: 'APHEX TWIN T-shirt',
    description: TSHIRT_DESCRIPTION,
    price: 30000,
    currency: 'ARS',
    category: 'wearing',
    images: { front: '/img/outfit/web/remera-frente-apextwin.webp', back: '/img/outfit/web/remera-espalda-apextwin.webp' },
    sizes: [],
    variants: ['S', 'M', 'L', 'XL'].map(size => ({ id: size, size, available: true })),
    colors: [],
    sizeGuide: TSHIRT_SIZE_GUIDE,
    featured: true,
    available: true,
    shipping: TSHIRT_SHIPPING,
    createdAt: '2026-10-08'
  },
  {
    id: 'lain-art-01',
    slug: 'lain-art-01',
    name: 'LAIN Framed Artwork',
    type: 'artwork',
    description: '',
    price: null,
    currency: 'ARS',
    category: 'Artwork',
    images: { artwork: '/img/outfit/web/lain-frame.webp' },
    imageFit: 'cover',
    featured: true,
    available: false,
    shipping: null,
    createdAt: '2026-09-28'
  }
];

export const categories = [...new Set(products.map(product => product.category))];
